artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/HAKIM-ML/Kidney-disease-classification-mlops/raw/main/short1.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/short.csv
  tokenizer_path: m2m100_tokenizer
  max_lenght: 128 
